# Generated by Django 4.0.1 on 2022-01-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date_initially_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
