# Generated by Django 4.0.1 on 2022-01-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0003_alter_enrichment_actual_activity_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='date_assigned_to_program_reviewer',
            field=models.DateField(null=True),
        ),
    ]
