# Generated by Django 3.2.7 on 2022-02-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0005_auto_20220205_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='assigned_state',
        ),
    ]
