# Generated by Django 4.0.1 on 2022-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0007_csvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvs',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
