# Generated by Django 4.0.1 on 2022-02-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0009_rename_activated_csvs_disaster_file_activated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvs',
            old_name='disaster_file_name',
            new_name='disaster_file',
        ),
    ]
