# Generated by Django 4.0.1 on 2022-02-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0012_alter_csvs_disaster_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasters',
            name='disaster_closeout_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
