# Generated by Django 4.0.1 on 2022-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0013_disasters_disaster_closeout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
