# Generated by Django 4.0.1 on 2022-02-22 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0014_alter_projects_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='assigned_project_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProjectManagementApp.projects'),
        ),
    ]
