# Generated by Django 4.0.1 on 2022-02-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0016_alter_enrichment_assigned_project_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='assigned_project_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManagementApp.projects'),
        ),
    ]
