# Generated by Django 4.0.1 on 2022-02-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApp', '0017_alter_enrichment_assigned_project_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='assigned_project_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManagementApp.projects'),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='project_deliverable_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='project_deliverable_title',
            field=models.CharField(max_length=100),
        ),
    ]
